### Data Encoding

Nominal/OHE Encoding

In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [7]:
## Creating DataFrame
df = pd.DataFrame({'Color': ['red', 'blue', 'green', 'green', 'red', 'blue']})

## Creating an instance of OneHotEncode
encoder = OneHotEncoder()

## Perform fit and transform
encoded = encoder.fit_transform(df[['Color']]).toarray()
encoded

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [8]:
encoded_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out())
encoded_df

   Color_blue  Color_green  Color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [ ]:
## For new coming data (let's say 'blue)
encoder.transform([['blue']]).toarray()

c:\Users\ermoh\OneDrive\Desktop\Data-Analyst\venv\Lib\site-packages\sklearn\utils\validation.py:2830: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [10]:
pd.concat([df, encoded_df], axis=1)

   Color  Color_blue  Color_green  Color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0