### Pandas - DataFrames and Series

Series

In [ ]:
## Creating series using a list

import pandas as pd

data = [1, 2, 3, 4, 5]

series = pd.Series(data)
print("Series:\n", series)

In [6]:
## Creating Series using a dictionary

data = {'a': 1, 'b': 2, 'c': 3}

series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [7]:
## Creating ou own index values

data = [10, 20 ,30]
index = ['a', 'b', 'c']
pd.Series(data, index = index)

a    10
b    20
c    30
dtype: int64

DataFrame

In [6]:
## Creatind DataFrame from a dictionary of list

data = {
    "Name": ["Krish", "John", "Jack"],
    "Age": [25, 30 ,35],
    "City": ["Bangalore", "New York", "Florida"]
}

df = pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   35    Florida
<class 'pandas.DataFrame'>

In [9]:
## Converting above DataFrame into an array using numpy

import numpy as np

np.array(df)

array([['Krish', 25, 'Bangalore'],
       ['John', 30, 'New York'],
       ['Jack', 35, 'Florida']], dtype=object)

In [6]:
## Creating a DataFrame from list of dictionaries

data = [
    {"Name": "Krish", "Age": 30, "City": "Bangalore"},
    {"Name": "John", "Age": 35, "City": "New York"},
    {"Name": "Jack", "Age": 40, "City": "Florida"}
]
df = pd.DataFrame(data)
print(df)

    Name  Age       City
0  Krish   30  Bangalore
1   John   35   New York
2   Jack   40    Florida

Performing operations on csv file

In [50]:
df = pd.read_csv('data.csv')

## Printing first 5 rows from DataFrame
df.head(5)

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [5]:
## Printing last 5 rows from DataFrame
df.tail(5)

          Date Category  Value   Product  Sales Region
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [51]:
## Display the data types of each column
print("Data types:\n", df.dtypes)
print("\n")
## Describe the DataFrame
print("Statistical Summary:\n", df.describe())

Data types:
 Date            str
Category        str
Value       float64
Product         str
Sales       float64
Region          str
dtype: object


Statistical Summary:
            Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000

In [4]:
## Accessing data from DataFrame

data

[1, 2, 3, 4, 5]

In [ ]:
## Accessing names

print(df['Name'])
print(type(df['Name']))

0    Krish
1     John
2     Jack
Name: Name, dtype: str
<class 'pandas.Series'>

In [11]:
## Accessing row content
print(df.loc[0])
print(type(df.loc[0]))

## Getting name from a particular row
print(df.loc[0, 'Name'])
print(df.loc[0]['City'])

Name        Krish
Age            30
City    Bangalore
Name: 0, dtype: object
<class 'pandas.Series'>
Krish
Bangalore

In [13]:
## Getting multiple rows
df.loc[0:1]

    Name  Age       City
0  Krish   30  Bangalore
1   John   35   New York

In [18]:
df.iloc[0]

Name        Krish
Age            30
City    Bangalore
Name: 0, dtype: object

In [22]:
df.iloc[0, 2]

'Bangalore'

In [22]:
df.iloc[0:1]

    Name  Age       City
0  Krish   25  Bangalore

In [36]:
df.at[0, 'Age'] = 25

In [33]:
## Accessing specified element

df.at[0, 'Age']

np.int64(30)

In [36]:
## Accessing specified element using iat

df.iat[1, 0]

'John'

In [38]:
## Adding a new column

df['Salary'] = [50000, 60000 , 70000]
df

    Name  Age       City  Salary
0  Krish   25  Bangalore   50000
1   John   30   New York   60000
2   Jack   35    Florida   70000

In [41]:
## Removing a column temporarily

df.drop('Salary', axis=1)

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   35    Florida

In [42]:
df

    Name  Age       City  Salary
0  Krish   25  Bangalore   50000
1   John   30   New York   60000
2   Jack   35    Florida   70000

In [43]:
## Now removing a column permanently

df.drop('Salary', axis=1, inplace=True)

In [44]:
df

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   35    Florida

In [45]:
## Increasing Age

df['Age'] = df['Age']+1
df

    Name  Age       City
0  Krish   26  Bangalore
1   John   31   New York
2   Jack   36    Florida

In [46]:
## Deleting on the basis of row temporarily

df.drop(0)

   Name  Age      City
1  John   31  New York
2  Jack   36   Florida

In [47]:
df

    Name  Age       City
0  Krish   26  Bangalore
1   John   31   New York
2   Jack   36    Florida

In [48]:
## Now permanently

df.drop(0, inplace=True)

In [49]:
df

   Name  Age      City
1  John   31  New York
2  Jack   36   Florida